Repository hmcts/pcs-frontend, pull requests merged in 2024-12, with the labels that each got.

#113 added healthcheck for api
  charts/pcs-frontend/Chart.yaml
  charts/pcs-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  src/main/routes/health.ts
  src/main/routes/info.ts
  yarn.lock
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-113

#114 HDPI-89 - Remove view count on application homepage
  src/main/routes/home.ts
  src/main/views/home.njk
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-114

#115 Migrate to playwright
  .gitignore
  .yarn/releases/yarn-4.5.3.cjs
  .yarnrc.yml
  Jenkinsfile_CNP
  codecept.conf.js
  codecept.conf.ts
  jest.a11y.config.js
  package.json
  playwright.config.ts
  src/test/a11y/a11y.ts
  src/test/a11y/dummy-test.ts
  src/test/functional/basic.spec.ts
  src/test/functional/features/hello-world.feature
  src/test/functional/steps.d.ts
  src/test/steps/common.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-115

#116 Adding unit tests
  src/test/unit/modules/appinsights/index.test.ts
  src/test/unit/routes/info.test.ts
  src/test/unit/sample.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-116

#126 HDPI-96 - Adding accessibility test helper
  Jenkinsfile_CNP
  package.json
  src/test/functional/basic.spec.ts
  src/test/functional/helpers/accessibilityTestHelper.ts
  yarn.lock
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-126

#133 HDPI-95 - Adding run chnaged tests helper
  package.json
  src/test/functional/helpers/runChangedTestHelper.ts
  yarn.lock
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-133

#140 Adding codeql.yaml
  .github/codeql/workflows/codeql.yaml
  yarn-audit-known-issues
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-140

#141 Adjusting workflows folder path to actually be accessible by github
  .github/workflows/codeql.yaml
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-141

#146 HDPI98
  Jenkinsfile_nightly
  package.json
  src/test/functional/basic.spec.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-146

#147 HDPI-100 - Updating README.md for testing
  Jenkinsfile_nightly
  README.md
  src/test/config.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-147

#152 Revert "Update dependency sass to v1.83.0"
  yarn.lock
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-152

#156 Bump version
  charts/pcs-frontend/Chart.yaml
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-156

#159 Downgrade redis to 20.3
  charts/pcs-frontend/Chart.yaml
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-159

#161 Removing deprecated request package
  .gitignore
  package.json
  yarn.lock
Labels: dependencies, ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-161

#171 Try using oci url as suggested by platops
  charts/pcs-frontend/Chart.yaml
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-171
