Repository hmcts/pcs-frontend, pull requests merged in 2025-04, with the labels that each got.

#293 Hdpi 359 postcode dummy page
  package.json
  src/main/routes/postcode.ts
  src/main/views/postcode-result.njk
  src/main/views/postcode.njk
  src/test/tsconfig.json
  src/test/unit/modules/appinsights/index.test.ts
  src/test/unit/routes/postcode.test.ts
  tsconfig.json
  yarn.lock
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-293

#310 HDPI-599: Minor updates to README
  README.md
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-310

#314 fix: accidental removal of pact-cli
  package.json
  yarn.lock
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-314

#320 docs: updated readme to use node v22
  README.md
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-320

#315 HDPI-611: Refactor out PCS API client
  src/main/routes/home.ts
  src/main/routes/postcode.ts
  src/main/services/pcsApi/courtVenue.interface.ts
  src/main/services/pcsApi/pcsApiService.ts
  src/test/unit/routes/postcode.test.ts
  src/test/unit/services/pcsApi/pcsApiService.test.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-315

#331 Hdp1 347 idam backend
  .dockerignore
  .env.example
  .gitignore
  Dockerfile
  config/custom-environment-variables.json
  config/default.json
  docker-compose.yml
  package.json
  src/main/app.ts
  src/main/development.ts
  src/main/modules/oidc/IdTokenJwtPayload.interface.ts
  src/main/modules/oidc/IdamResponseData.interface.ts
  src/main/modules/oidc/index.ts
  src/main/modules/oidc/oidc.ts
  src/main/modules/session/index.ts
  src/main/routes/health.ts
  src/main/server.ts
  src/test/unit/middleware/oidc.test.ts
  src/test/unit/modules/oidc/oidc.test.ts
  src/types/global.d.ts
  yarn.lock
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-331

#329 Hdpi 515 display court name refactoring
  charts/pcs-frontend/Chart.yaml
  src/main/interface/courtVenue.interface.ts
  src/main/modules/helmet/index.ts
  src/main/routes/postcode.ts
  src/main/services/pcsApi/courtVenue.interface.ts
  src/main/services/pcsApi/pcsApiService.ts
  src/main/views/courts.njk
  src/main/views/postcode-result.njk
  src/test/unit/routes/postcode.test.ts
  src/test/unit/services/pcsApi/pcsApiService.test.ts
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-329
