Repository hmcts/pcs-frontend, pull requests merged in 2025-06, with the labels that each got.

#394 Updated test folder structure and UI tests and
  config/custom-environment-variables.json
  config/default.json
  playwright.config.ts
  sonar-project.properties
  src/test/config.ts
  src/test/e2e/page-objects/pages/cui/landing.ts
  src/test/functional/basic.spec.ts
  src/test/routes/home.ts
  src/test/smoke/smoke.spec.ts
  src/test/ui/common/data/constants.data.json
  src/test/ui/common/data/index.ts
  src/test/ui/common/data/testData.data.json
  src/test/ui/common/helpers/accessibility.helper.ts
  src/test/ui/common/helpers/element-helpers/index.ts
  src/test/ui/common/helpers/element-helpers/webElements.helper.ts
  src/test/ui/common/helpers/index.ts
  src/test/ui/common/helpers/login.helper.ts
  src/test/ui/common/helpers/testConfig.ts
  src/test/ui/common/helpers/testRunner.helper.ts
  src/test/ui/common/helpers/user-helpers/idam.helper.ts
  src/test/ui/common/helpers/user-helpers/rest.helper.ts
  src/test/ui/common/helpers/user-helpers/retry.helper.js
  src/test/ui/common/page-objects/base.ts
  src/test/ui/common/page-objects/claimForm.po.ts
  src/test/ui/common/page-objects/home.po.ts
  src/test/ui/common/page-objects/index.ts
  src/test/ui/common/page-objects/login.po.ts
  src/test/ui/functional/home.spec.ts
  src/test/unit/app/controller/controllerFactory.test.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-394

#395 HDPI-798
  src/test/contract/consumer/IdamConsumer.test.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-395

#402 Functional test temporarily disabled
  src/test/ui/functional/home.spec.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-402

#421 fix: incorrect redirect uri in staging
  charts/pcs-frontend/Chart.yaml
  charts/pcs-frontend/values.aat.template.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-421

#424 Resumed functional testing in pcs-frontend
  Jenkinsfile_CNP
  README.md
  playwright.config.ts
  src/test/ui/functional/home.spec.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-424

#433 feat: Hdpi 143 idam retry
  src/main/modules/oidc/oidc.ts
  src/test/unit/modules/oidc/oidc.test.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-433

#438 fix: bugfix for lint issues
  .eslintignore
  .eslintrc.js
  eslint.config.js
  package.json
  src/main/routes/home.ts
  src/test/unit/modules/s2s/index.test.ts
  yarn.lock
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-438

#432 Created common components using relative pattern method
  playwright.config.ts
  src/test/ui/common/data/constants.data.json
  src/test/ui/common/helpers/element-helpers/actions.helper.ts
  src/test/ui/common/helpers/element-helpers/index.ts
  src/test/ui/common/helpers/element-helpers/webElements.helper.ts
  src/test/ui/common/helpers/idam-helpers/idam.helper.ts
  src/test/ui/common/helpers/idam-helpers/rest.helper.ts
  src/test/ui/common/helpers/idam-helpers/retry.helper.js
  src/test/ui/common/helpers/idam-helpers/testConfig.ts
  src/test/ui/common/helpers/login.helper.ts
  src/test/ui/common/page-objects/base.ts
  src/test/ui/common/page-objects/claimForm.po.ts
  src/test/ui/common/page-objects/home.po.ts
  src/test/ui/common/page-objects/index.ts
  src/test/ui/common/page-objects/login.po.ts
  src/test/ui/functional/home.spec.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-432

#443 fix: removed dummy files in place of API call
  Dockerfile
  src/main/assets/fixtures/taskgroups.json
  src/main/services/pcsApi/pcsApiService.ts
  src/test/unit/services/pcsApi/pcsApiService.test.ts
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-443

#457 Upping OIDC code coverage
  src/test/unit/modules/oidc/oidc.test.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-457
