Repository hmcts/pcs-frontend, pull requests merged in 2025-07, with the labels that each got.

#470 House Keeping work: removing process.env to access variables
  Jenkinsfile_CNP
  src/test/ui/common/helpers/idam-helpers/idam.helper.ts
  src/test/ui/common/helpers/login.helper.ts
  src/test/ui/functional/dashboard.spec.ts
  src/test/ui/functional/home.spec.ts
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-470

#475 HDPI-1253
  Jenkinsfile_CNP
  README.md
  config/custom-environment-variables.json
  config/default.json
  config/test.json
  src/test/ui/common/helpers/idam-helpers/idam.helper.ts
  src/test/ui/common/helpers/login.helper.ts
  src/test/ui/functional/dashboard.spec.ts
  src/test/ui/functional/home.spec.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-475

#478 New tests added for Possession claim journeys with framework improvements
  config/test.json
  playwright.config.ts
  src/test/ui/common/data/index.ts
  src/test/ui/common/data/testData.data.json
  src/test/ui/common/helpers/element-helpers/actions.helper.ts
  src/test/ui/common/helpers/element-helpers/index.ts
  src/test/ui/common/helpers/element-helpers/verification.helper.ts
  src/test/ui/common/helpers/idam-helpers/idam.helper.ts
  src/test/ui/common/helpers/index.ts
  src/test/ui/common/helpers/login.helper.ts
  src/test/ui/config/global-setup.config.ts
  src/test/ui/config/global-teardown.config.ts
  src/test/ui/data/constants.data.json
  src/test/ui/data/dashboard.ts
  src/test/ui/data/index.ts
  src/test/ui/functional/dashboard.spec.ts
  src/test/ui/functional/home.spec.ts
  src/test/ui/functional/possessionClaims.spec.ts
  src/test/ui/utils/actions/custom-actions/login.action.ts
  src/test/ui/utils/actions/custom-actions/navigateToUrl.action.ts
  src/test/ui/utils/actions/element-actions/check.action.ts
  src/test/ui/utils/actions/element-actions/clickButton.action.ts
  src/test/ui/utils/actions/element-actions/clickRadioButton.action.ts
  src/test/ui/utils/actions/element-actions/fill.action.ts
  src/test/ui/utils/controller.ts
  src/test/ui/utils/helpers/accessibility.helper.ts
  src/test/ui/utils/helpers/idam-helpers/idam.helper.ts
  src/test/ui/utils/helpers/idam-helpers/rest.helper.ts
  src/test/ui/utils/helpers/idam-helpers/retry.helper.js
  src/test/ui/utils/helpers/idam-helpers/testConfig.ts
  src/test/ui/utils/helpers/testRunner.helper.ts
  src/test/ui/utils/interfaces/action.interface.ts
  src/test/ui/utils/interfaces/validation.interface.ts
  src/test/ui/utils/registry/action.registry.ts
  src/test/ui/utils/registry/validation.registry.ts
  src/test/ui/utils/validations/custom-validations/dashboardNotification.validation.ts
  src/test/ui/utils/validations/custom-validations/dashboardTasks.validation.ts
  src/test/ui/utils/validations/element-validations/attribute.validation.ts
  src/test/ui/utils/validations/element-validations/checked.validation.ts
  src/test/ui/utils/validations/element-validations/count.validation.ts
  src/test/ui/utils/validations/element-validations/css.validation.ts
  src/test/ui/utils/validations/element-validations/enabled.validation.ts
  src/test/ui/utils/validations/element-validations/pageTitle.validation.ts
  src/test/ui/utils/validations/element-validations/text.validation.ts
  src/test/ui/utils/validations/element-validations/value.validation.ts
  src/test/ui/utils/validations/element-validations/visibility.validation.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-478

#496 chore: audit issues
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-496

#488 Hdpi 857 form builder journey
  .env.example
  Dockerfile
  JOURNEY_ENGINE_README.md
  charts/pcs-frontend/values.preview.template.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  sonar-project.properties
  src/main/app.ts
  src/main/assets/scss/main.scss
  src/main/journeys/eligibility/index.ts
  src/main/journeys/eligibility/steps/confirmation/confirmation.njk
  src/main/journeys/eligibility/steps/confirmation/step.ts
  src/main/journeys/eligibility/steps/ineligible/ineligible.njk
  src/main/journeys/eligibility/steps/ineligible/step.ts
  src/main/journeys/eligibility/steps/page2/step.ts
  src/main/journeys/eligibility/steps/page3/step.ts
  src/main/journeys/eligibility/steps/page4/step.ts
  src/main/journeys/eligibility/steps/page5/step.ts
  src/main/journeys/eligibility/steps/start/start.njk
  src/main/journeys/eligibility/steps/start/step.ts
  src/main/journeys/eligibility/steps/summary/step.ts
  src/main/journeys/example/index.ts
  src/main/modules/appinsights/index.ts
  src/main/modules/helmet/index.ts
  src/main/modules/index.ts
  src/main/modules/journey/engine/engine.ts
  src/main/modules/journey/engine/errorUtils.ts
  src/main/modules/journey/engine/schema.ts
  src/main/modules/journey/engine/storage/ccdStore.ts
  src/main/modules/journey/engine/storage/databaseStore.ts
  src/main/modules/journey/engine/storage/index.ts
  src/main/modules/journey/engine/storage/journeyStore.interface.ts
  src/main/modules/journey/engine/storage/memoryStore.ts
  src/main/modules/journey/engine/storage/redisStore.ts
  src/main/modules/journey/engine/storage/sessionStore.ts
  src/main/modules/journey/engine/validation.ts
  src/main/modules/journey/index.ts
  src/main/modules/journey/journey.ts
  src/main/modules/launch-darkly/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/oidc/oidc.ts
  src/main/server.ts
  src/main/utils/ttlCache.ts
  src/main/views/_defaults/confirmation.njk
  src/main/views/_defaults/form.njk
  src/main/views/_defaults/ineligible.njk
  src/main/views/_defaults/summary.njk
  src/main/views/stepsTemplate.njk
  src/main/views/template.njk
  src/test/unit/modules/appinsights/index.test.ts
  src/test/unit/modules/journey/engine/buttonField.test.ts
  src/test/unit/modules/journey/engine/errorUtils.test.ts
  src/test/unit/modules/journey/journey.test.ts
  src/test/unit/modules/launch-darkly/index.test.ts
  src/test/unit/modules/nunjucks/index.test.ts
  src/test/unit/utils/ttlCache.test.ts
  tsconfig.json
  yarn.lock
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-488
