Repository hmcts/pcs-frontend, pull requests merged in 2025-05, with the labels that each got.

#345 debug: added logging for debug oidc issues
  src/main/modules/oidc/oidc.ts
  yarn-audit-known-issues
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-345

#342 Hdpi 500 dashboard UI branch 2
  package.json
  src/main/modules/nunjucks/filters/currency.ts
  src/main/modules/nunjucks/filters/date.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/routes/dashboard.ts
  src/main/services/pcsApi/dashboardNotification.interface.ts
  src/main/services/pcsApi/index.ts
  src/main/services/pcsApi/pcsApiService.ts
  src/main/views/components/notification/Notice.AAA3.ClaimIssue.ClaimSubmit.Required.njk
  src/main/views/components/notification/Notice.AAA3.DefResponse.MoreTimeRequested.Defendant.njk
  src/main/views/components/notification/Notice.AAA3.DefResponse.ResponseTimeElapsed.Claimant.njk
  src/main/views/components/notification/macro.njk
  src/main/views/dashboard.njk
  src/test/unit/modules/nunjucks/filters/currency.test.ts
  src/test/unit/modules/nunjucks/filters/date.test.ts
  src/test/unit/modules/nunjucks/index.test.ts
  src/test/unit/routes/dashboard.test.ts
  src/test/unit/services/pcsApi/pcsApiService.test.ts
  src/types/global.d.ts
  yarn.lock
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-342

#349 fix: removed extra params from login and also implemented logout feature
  src/main/modules/oidc/oidc.ts
  src/main/views/home.njk
  src/main/views/template.njk
  src/test/unit/modules/oidc/oidc.test.ts
  src/types/global.d.ts
  yarn-audit-known-issues
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-349

#346 Hdpi-645 create idam user
  .env.example
  Jenkinsfile_CNP
  README.md
  bin/dev/createIdamUser.sh
  package.json
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-346

#364 feat: Hdpi 511 dashboard task groups
  Dockerfile
  docker-compose.yml
  nodemon.json
  package.json
  src/main/assets/fixtures/taskgroups.json
  src/main/middleware/oidc.ts
  src/main/modules/oidc/oidc.ts
  src/main/modules/s2s/index.ts
  src/main/modules/session/index.ts
  src/main/routes/dashboard.ts
  src/main/services/pcsApi/dashboardTaskGroup.interface.ts
  src/main/services/pcsApi/index.ts
  src/main/services/pcsApi/pcsApiService.ts
  src/main/views/components/taskGroup/applications/Task.AAA6.Applications.Contact.njk
  src/main/views/components/taskGroup/applications/Task.AAA6.Applications.ViewApplications.njk
  src/main/views/components/taskGroup/claim/Task.AAA6.Claim.Adjustments.njk
  src/main/views/components/taskGroup/claim/Task.AAA6.Claim.Equality.njk
  src/main/views/components/taskGroup/claim/Task.AAA6.Claim.Information.njk
  src/main/views/components/taskGroup/claim/Task.AAA6.Claim.ViewClaim.njk
  src/main/views/components/taskGroup/hearing/Task.AAA6.Hearing.PayFee-hint.njk
  src/main/views/components/taskGroup/hearing/Task.AAA6.Hearing.PayFee.njk
  src/main/views/components/taskGroup/hearing/Task.AAA6.Hearing.TrialArrangments.njk
  src/main/views/components/taskGroup/hearing/Task.AAA6.Hearing.UploadDocuments-hint.njk
  src/main/views/components/taskGroup/hearing/Task.AAA6.Hearing.UploadDocuments.njk
  src/main/views/components/taskGroup/hearing/Task.AAA6.Hearing.ViewBundle.njk
  src/main/views/components/taskGroup/hearing/Task.AAA6.Hearing.ViewDocuments.njk
  src/main/views/components/taskGroup/hearing/Task.AAA6.Hearing.ViewHearing.njk
  src/main/views/components/taskGroup/judgement/Task.AAA6.Judgement.ViewJudgement.njk
  src/main/views/components/taskGroup/macro.njk
  src/main/views/components/taskGroup/notice/Task.AAA6.Notice.ViewNotices.njk
  src/main/views/components/taskGroup/response/Task.AAA6.Response.Information.njk
  src/main/views/components/taskGroup/response/Task.AAA6.Response.ViewResponse.njk
  src/main/views/dashboard.njk
  src/test/unit/middleware/oidc.test.ts
  src/test/unit/routes/dashboard.test.ts
  src/types/global.d.ts
  yarn.lock
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-364

#367 HDPI-694
  .env.example
  Jenkinsfile_CNP
  config/custom-environment-variables.json
  config/default.json
  src/test/config.ts
  src/test/e2e/TestConfig.ts
  src/test/e2e/helpers/accessibilityTestHelper.ts
  src/test/e2e/helpers/runChangedTestHelper.ts
  src/test/e2e/helpers/userHelpers/IdamHelper.ts
  src/test/e2e/helpers/userHelpers/restHelper.ts
  src/test/e2e/helpers/userHelpers/retryHelper.js
  src/test/e2e/page-objects/base.ts
  src/test/e2e/page-objects/pages/cui/landing.ts
  src/test/e2e/page-objects/pages/idam.login.ts
  src/test/functional/basic.spec.ts
  yarn-audit-known-issues
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-367

#379 Hdpi 698 customer journey step navigation 2
  jest.config.js
  sonar-project.properties
  src/main/app.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/controllerFactory.ts
  src/main/app/controller/sessionHelper.ts
  src/main/app/controller/validation.ts
  src/main/assets/locales/en/common.json
  src/main/assets/locales/en/page1.json
  src/main/assets/locales/en/page2.json
  src/main/assets/locales/en/page3No.json
  src/main/assets/locales/en/page3Yes.json
  src/main/assets/locales/en/page4.json
  src/main/interfaces/courtVenue.interface.ts
  src/main/interfaces/formFieldConfig.interface.ts
  src/main/interfaces/stepFormData.interface.ts
  src/main/routes/registerSteps.ts
  src/main/services/pcsApi/courtVenue.interface.ts
  src/main/services/pcsApi/pcsApiService.ts
  src/main/steps/index.ts
  src/main/steps/page1/index.ts
  src/main/steps/page2/index.ts
  src/main/steps/page3No/index.ts
  src/main/steps/page3Yes/index.ts
  src/main/steps/page4/index.ts
  src/main/views/steps/page1.njk
  src/main/views/steps/page2.njk
  src/main/views/steps/page3No.njk
  src/main/views/steps/page3Yes.njk
  src/main/views/steps/page4.njk
  src/main/views/stepsTemplate.njk
  src/test/unit/app/controller/controllerFactory.test.ts
  src/test/unit/app/controller/sessionHelper.test.ts
  src/test/unit/app/controller/validation.test.ts
  src/test/unit/routes/registerSteps.test.ts
  src/test/unit/services/pcsApi/pcsApiService.test.ts
  src/types/global.d.ts
  tsconfig.json
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-379

#372 fix: s2s token not being picked up correctly, refactored
  config/custom-environment-variables.json
  config/default.json
  jest.config.js
  sonar-project.properties
  src/main/modules/http/index.ts
  src/main/modules/index.ts
  src/main/modules/s2s/index.ts
  src/main/modules/s2s/s2s.interface.ts
  src/main/routes/dashboard.ts
  src/main/server.ts
  src/main/services/pcsApi/dashboardTaskGroup.interface.ts
  src/main/services/pcsApi/pcsApiService.ts
  src/main/views/components/taskGroup/applications/Task.AAA6.Applications.Contact.njk
  src/test/unit/modules/http/http.test.ts
  src/test/unit/modules/s2s/__mocks__/jose.ts
  src/test/unit/modules/s2s/index.test.ts
  src/test/unit/routes/dashboard.test.ts
  src/test/unit/services/pcsApi/pcsApiService.test.ts
  src/types/courtVenue.interface.ts
  src/types/global.d.ts
Labels: ns:pcs, prd:pcs, enable_keep_helm, rel:pcs-frontend-pr-372

#384 HDPI-763 Idam consumer pact tests
  Jenkinsfile_CNP
  src/test/contract/consumer/IdamConsumer.test.ts
  src/test/contract/consumer/ServiceAuthorisation.test.ts
Labels: ns:pcs, prd:pcs, rel:pcs-frontend-pr-384
